apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-currency-provider
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-demo-currency-provider
  type: NodePort